import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const packageDirectory = join(scriptDirectory, '..');
const schemaPath = join(packageDirectory, 'vendor', 'td', 'td', 'generate', 'scheme', 'td_api.tl');
const outputPath = join(packageDirectory, 'src', 'generated', 'td-api.ts');

async function readSubmoduleCommit(): Promise<string> {
  const gitFile = await readFile(join(packageDirectory, 'vendor', 'td', '.git'), 'utf8');
  const gitDirectory = resolve(
    join(packageDirectory, 'vendor', 'td'),
    gitFile.replace(/^gitdir:\s*/, '').trim(),
  );
  const head = (await readFile(join(gitDirectory, 'HEAD'), 'utf8')).trim();
  if (!head.startsWith('ref: ')) return head;
  return (await readFile(join(gitDirectory, head.slice(5)), 'utf8')).trim();
}

interface Declaration {
  readonly name: string;
  readonly result: string;
  readonly fields: readonly Field[];
}

interface Field {
  readonly name: string;
  readonly type: string;
}

const pascal = (value: string): string => value[0].toUpperCase() + value.slice(1);

function parseDeclarations(source: string): { objects: Declaration[]; functions: Declaration[] } {
  const sections = source.split(/^---functions---$/m);
  const primitiveAliases = new Set([
    'double',
    'string',
    'int32',
    'int53',
    'int64',
    'bytes',
    'boolFalse',
    'boolTrue',
    'vector',
  ]);
  if (sections.length !== 2) throw new Error('TDLib schema does not contain the functions marker');

  const parse = (section: string): Declaration[] => {
    const declarations: Declaration[] = [];
    for (const rawLine of section.split('\n')) {
      const line = rawLine.trim();
      if (!line || line.startsWith('//') || line.includes(' ? ')) continue;
      const match = /^(\w+)(?:\s+\{[^}]+\})?\s*(.*?)\s*=\s*(\w+)(?:\s+\w+)?;$/.exec(line);
      if (!match || primitiveAliases.has(match[1])) continue;
      const [, name, fieldSource, result] = match;
      const fields = [...fieldSource.matchAll(/(\w+):(vector<[^\s]+>|\w+)/g)].map((field) => ({
        name: field[1],
        type: field[2],
      }));
      declarations.push({ name, result, fields });
    }
    return declarations;
  };

  return { objects: parse(sections[0]), functions: parse(sections[1]) };
}

function renderType(type: string, nullable = false): string {
  const vector = /^vector<(.+)>$/.exec(type);
  if (vector) return `TdVector<${renderType(vector[1])}>`;
  if (
    type === 'double' ||
    type === 'Double' ||
    type === 'int32' ||
    type === 'Int32' ||
    type === 'int53' ||
    type === 'Int53' ||
    type === 'int64' ||
    type === 'Int64'
  )
    return 'number';
  if (type === 'string' || type === 'String' || type === 'bytes' || type === 'Bytes')
    return 'string';
  if (type === 'bool' || type === 'Bool' || type === 'boolFalse' || type === 'boolTrue')
    return 'boolean';
  return `Td${pascal(type)}${nullable ? ' | null' : ''}`;
}

function renderObject(declaration: Declaration): string {
  const fields = declaration.fields
    .map((field) => `  ${field.name}: ${renderType(field.type, true)};`)
    .join('\n');
  return `export interface Td${pascal(declaration.name)} {\n  readonly "@type": '${declaration.name}';${fields ? `\n${fields}` : ''}\n}`;
}

function renderUnion(name: string, declarations: readonly Declaration[]): string {
  const members = declarations
    .filter((declaration) => declaration.result === name)
    .map((declaration) => `Td${pascal(declaration.name)}`);
  return members.length > 1 ? `export type Td${pascal(name)} = ${members.join(' | ')};` : '';
}

function render(source: string, commit: string): string {
  const { objects, functions } = parseDeclarations(source);
  const resultNames = [...new Set(objects.map((declaration) => declaration.result))].toSorted();
  const functionResults = functions
    .map((declaration) => `  '${declaration.name}': Td${pascal(declaration.result)};`)
    .join('\n');
  const functionRequests = functions
    .map((declaration) => `Td${pascal(declaration.name)}`)
    .join(' |\n  ');
  const objectDefinitions = objects.map(renderObject).join('\n\n');
  const unions = resultNames
    .map((name) => renderUnion(name, objects))
    .filter(Boolean)
    .join('\n');
  const requestDefinitions = functions.map(renderObject).join('\n\n');
  const schemaHash = createHash('sha256').update(source).digest('hex');

  return `// This file is generated by scripts/generate-types.ts.\n// TDLib commit: ${commit}\n// TDLib schema sha256: ${schemaHash}\n\n/** A JSON array generated by TDLib's vector type. / Массив JSON, соответствующий vector TDLib. @public */\nexport type TdVector<T> = T[];\n\n${objectDefinitions}\n\n${unions}\n\n${requestDefinitions}\n\n/** Complete union of TDLib function requests. / Полное объединение запросов функций TDLib. @public */\nexport type TdRequest =\n  ${functionRequests};\n\n/** Maps every TDLib function request type to its result type. / Сопоставляет каждый запрос TDLib с типом результата. @public */\nexport interface TdResultMap {\n${functionResults}\n}\n\n/** Result type inferred from a typed TDLib request. / Тип результата, выведенный из типизированного запроса TDLib. @public */\nexport type TdResultFor<T extends TdRequest> = T['@type'] extends keyof TdResultMap ? TdResultMap[T['@type']] : never;\n`;
}

const source = await readFile(schemaPath, 'utf8');
const resolvedCommit = await readSubmoduleCommit();
await writeFile(outputPath, render(source, resolvedCommit));
