import { spawnSync } from 'node:child_process';
import { mkdtemp, mkdir, readdir, readFile, rm, stat, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import process from 'node:process';
import { pathToFileURL } from 'node:url';

const root = path.resolve(import.meta.dirname, '..');
const publicEntrypoint = path.join(root, 'src', 'index.ts');
const documentationModule = pathToFileURL(
  path.join(root, 'node_modules', 'documentation', 'src', 'index.js'),
).href;
const githubSluggerModule = pathToFileURL(
  path.join(root, 'node_modules', 'github-slugger', 'index.js'),
).href;
const formatterCli = path.join(root, 'node_modules', '.bin', 'oxfmt');
const accessLevels = ['public', 'private', 'protected', 'undefined'];
const generatedNotice =
  '<!-- Generated by documentation.js. Update this documentation by updating the source code. -->';

async function publicExports(): Promise<Map<string, Set<string>>> {
  const source = await readFile(publicEntrypoint, 'utf8');
  const exportsByFile = new Map<string, Set<string>>();
  const pattern = /export\s+(?:type\s+)?\{([\s\S]*?)\}\s+from\s+['"]([^'"]+)['"];?/g;
  for (const match of source.matchAll(pattern)) {
    const file = path.resolve(path.dirname(publicEntrypoint), match[2]);
    const names = exportsByFile.get(file) ?? new Set<string>();
    for (const specifier of match[1].split(',')) {
      const name = specifier
        .trim()
        .replace(/^type\s+/, '')
        .split(/\s+as\s+/)[0];
      if (name.length > 0) names.add(name);
    }
    exportsByFile.set(file, names);
  }
  if (exportsByFile.size === 0) throw new Error('The public entrypoint exports no symbols');
  return exportsByFile;
}

function formatMarkdown(files: any[]) {
  const result = spawnSync(formatterCli, files, { cwd: root, stdio: 'inherit' });
  if (result.error) throw result.error;
  if (result.status !== 0) process.exit(result.status ?? 1);
}

function documentationBlock(comment: any, source: string): string {
  return source.slice(comment.loc.start.index, comment.loc.end.index);
}

function hasAccessTag(comment: any, source: string, access: string): boolean {
  const block = documentationBlock(comment, source);
  return new RegExp(`@(?:access\\s+)?${access}\\b`).test(block);
}

function stripRenderedAccessTags(value: any, visited = new WeakSet<object>()): void {
  if (value === null || typeof value !== 'object' || visited.has(value)) return;
  visited.add(value);
  if (typeof value.value === 'string') {
    value.value = value.value.replace(/\s+@(public|private|protected)\b/g, '');
  }
  for (const child of Object.values(value)) stripRenderedAccessTags(child, visited);
}

function publicInterface(comment: any, source: string): any {
  for (const scope of Object.keys(comment.members ?? {})) {
    comment.members[scope] = comment.members[scope]
      .filter(
        (member: any) =>
          member.access !== 'private' &&
          member.access !== 'protected' &&
          !hasAccessTag(member, source, 'private') &&
          !hasAccessTag(member, source, 'protected'),
      )
      .map((member: any) => publicInterface(member, source));
  }
  stripRenderedAccessTags(comment);
  return comment;
}

function checkExportAccess(comments: any[], source: string, file: string): void {
  const commentsByDeclaration = new Map(
    comments.map((comment: any) => [comment.context.loc.start.index, comment]),
  );
  const invalid: string[] = [];
  const declarationPattern =
    /^export\s+(?:(?:default|abstract|async)\s+)*(?:class|interface|type|function|const)\s+([A-Za-z_$][\w$]*)/gm;
  for (const match of source.matchAll(declarationPattern)) {
    const comment = commentsByDeclaration.get(match.index);
    if (!comment) {
      invalid.push(`${match[1]} has no JSDoc`);
      continue;
    }
    const tags = ['public', 'private', 'protected'].filter((access: string) =>
      hasAccessTag(comment, source, access),
    );
    if (tags.length !== 1)
      invalid.push(`${match[1]} has access tags: ${tags.join(', ') || 'none'}`);
  }
  if (invalid.length === 0) return;
  throw new Error(`Invalid exported JSDoc in ${path.relative(root, file)}:\n${invalid.join('\n')}`);
}

function declarationText(comment: any, source: string): string | undefined {
  const declaration = source.slice(comment.context.loc.start.index, comment.context.loc.end.index);
  return /^export\s+(interface|type)\b/.test(declaration) ? declaration : undefined;
}

function declarationsMarkdown(comments: any[], source: string): string {
  const declarations = comments
    .map((comment: any) => ({ name: comment.name, text: declarationText(comment, source) }))
    .filter((declaration: any) => declaration.text !== undefined);
  if (declarations.length === 0) return '';
  const sections = declarations
    .map(
      (declaration: any) => `### \`${declaration.name}\`\n\n\`\`\`ts\n${declaration.text}\n\`\`\``,
    )
    .join('\n\n');
  return `\n\n## TypeScript declarations / TypeScript-декларации\n\n${sections}\n`;
}

function slug(name: string): string {
  return name.toLowerCase();
}

function capability(name: string): string {
  if (
    ['Application', 'ApplicationOptions', 'ApplicationStateError', 'ListenOptions'].includes(name)
  )
    return 'Application';
  if (name.includes('Http')) return 'HTTP';
  if (name.includes('WebSocket')) return 'WebSocket';
  if (name.includes('Event')) return 'Events';
  if (name.includes('Job') || name === 'WorkerTerminatedError') return 'Jobs';
  return 'Middleware';
}

function capabilityGuide(name: string): string {
  const guides = new Map([
    ['Application', 'application.md'],
    ['HTTP', 'http.md'],
    ['WebSocket', 'websocket.md'],
    ['Events', 'application-events.md'],
    ['Jobs', 'jobs.md'],
    ['Middleware', 'middleware.md'],
  ]);
  return guides.get(name) ?? 'README.md';
}

function linkCrossModuleTypes(
  markdown: string,
  moduleName: string,
  symbols: Map<string, any>,
): string {
  const linkedReferences = markdown.replace(
    /^(\[\d+\]: )([A-Za-z_$][\w$]*)(?:#([A-Za-z_$][\w$]*))?$/gm,
    (line: string, prefix: string, name: string, member: string | undefined) => {
      const target = symbols.get(name);
      if (!target) return line;
      const anchor = member === undefined ? target.anchor : slug(member);
      return `${prefix}./${target.module}.md#${anchor}`;
    },
  );
  let linkedTypes = linkedReferences;
  for (const [name, target] of symbols) {
    if (target.module === moduleName) continue;
    linkedTypes = linkedTypes.replaceAll(
      `**${name}**`,
      `**[${name}](./${target.module}.md#${target.anchor})**`,
    );
  }
  return linkedTypes;
}

function moduleMarkdown(
  name: string,
  markdown: string,
  declarations: string,
  symbols: Map<string, any>,
): string {
  const linked = linkCrossModuleTypes(markdown, name, symbols);
  return (
    linked.replace(
      generatedNotice,
      `${generatedNotice}\n\n# ${name}\n\nSource / Исходный модуль: [\`lib/framework/${name}.ts\`](../../lib/framework/${name}.ts)`,
    ) + declarations
  );
}

function indexMarkdown(modules: any[]): string {
  const capabilities = new Map<string, any[]>();
  for (const module of modules) {
    for (const symbol of module.symbols) {
      const group = capability(symbol.name);
      const entries = capabilities.get(group) ?? [];
      entries.push(symbol);
      capabilities.set(group, entries);
    }
  }
  const capabilityEntries = ['Application', 'HTTP', 'WebSocket', 'Events', 'Jobs', 'Middleware']
    .filter((name: string) => capabilities.has(name))
    .map((name: string) => {
      const links = (capabilities.get(name) ?? [])
        .map((symbol: any) => `[\`${symbol.name}\`](api/${symbol.module}.md#${symbol.anchor})`)
        .join(', ');
      return `### [${name}](interface/${capabilityGuide(name)})\n\n${links}`;
    })
    .join('\n\n');
  const moduleEntries = modules
    .map(
      (module: any) =>
        `- [${module.name}](api/${module.name}.md) — ${module.symbols.length} public entities / публичных сущностей`,
    )
    .join('\n');
  return `${generatedNotice}

# API Documentation / API-документация

Public framework interface grouped by caller capability and source module. / Публичный интерфейс
фреймворка, сгруппированный по пользовательским возможностям и исходным модулям.

The explicit exports of [\`src/index.ts\`](../src/index.ts) are the source of truth for this list. /
Явные экспорты [\`src/index.ts\`](../src/index.ts) являются источником истины для этого списка.

Behavioral invariants, ADRs, examples, and seam tests: [interface map](interface/README.md). /
Поведенческие инварианты, ADR, примеры и seam-тесты: [карта interface](interface/README.md).

Errors by operation and observable effect: [error map](interface/errors.md). / Ошибки по операциям и
наблюдаемым эффектам: [карта ошибок](interface/errors.md).

## By capability / По возможностям

${capabilityEntries}

## Source modules / Исходные модули

${moduleEntries}
`;
}

async function generate(outputRoot: any) {
  const documentation: any = await import(documentationModule);
  const apiRoot = path.join(outputRoot, 'api');
  await mkdir(apiRoot, { recursive: true });
  const modules: any[] = [];
  const exportsByFile = await publicExports();

  for (const [file, exportedNames] of [...exportsByFile].toSorted(([left], [right]) =>
    left.localeCompare(right),
  )) {
    const source = await readFile(file, 'utf8');
    const comments = await documentation.build([file], {
      access: accessLevels,
      shallow: true,
    });
    checkExportAccess(comments, source, file);
    const publicComments = comments
      .filter(
        (comment: any) =>
          exportedNames.has(comment.name) && hasAccessTag(comment, source, 'public'),
      )
      .map((comment: any) => publicInterface(comment, source));
    const documentedNames = new Set(publicComments.map((comment: any) => comment.name));
    const undocumented = [...exportedNames].filter((name: string) => !documentedNames.has(name));
    if (undocumented.length > 0) {
      throw new Error(
        `Public entrypoint exports undocumented or non-public symbols from ${path.relative(root, file)}:\n${undocumented.join('\n')}`,
      );
    }
    if (publicComments.length === 0) continue;

    const name = path.basename(file, '.ts');
    modules.push({
      comments: publicComments,
      declarations: declarationsMarkdown(publicComments, source),
      name,
      output: path.join(apiRoot, `${name}.md`),
      symbols: publicComments.map((comment: any) => ({
        anchor: slug(comment.name),
        module: name,
        name: comment.name,
      })),
    });
  }

  const symbols = new Map<string, any>();
  for (const module of modules) {
    for (const symbol of module.symbols) symbols.set(symbol.name, symbol);
  }
  for (const module of modules) {
    const markdown = await documentation.formats.md(module.comments);
    await writeFile(
      module.output,
      moduleMarkdown(module.name, markdown, module.declarations, symbols),
    );
  }
  const index = path.join(outputRoot, 'API.md');
  await writeFile(index, indexMarkdown(modules));
  formatMarkdown([index, ...modules.map((module: any) => module.output)]);
}

async function listFiles(directory: any, prefix: any = '') {
  const entries = await readdir(directory, { withFileTypes: true });
  const files: any[] = [];
  for (const entry of entries.toSorted((left: any, right: any) =>
    left.name.localeCompare(right.name),
  )) {
    const relative = path.join(prefix, entry.name);
    if (entry.isDirectory())
      files.push(...(await listFiles(path.join(directory, entry.name), relative)));
    else files.push(relative);
  }
  return files;
}

async function generatedFiles(directory: any) {
  try {
    return ['API.md', ...(await listFiles(path.join(directory, 'api'), 'api'))];
  } catch (error: any) {
    if (error.code === 'ENOENT') return ['API.md'];
    throw error;
  }
}

function markdownTargets(markdown: string): string[] {
  const inline = [...markdown.matchAll(/\[[^\]]*\]\(([^)]+)\)/g)].map((match: any) => match[1]);
  const references = [...markdown.matchAll(/^\[[^\]]+\]:\s+(\S+)/gm)].map((match: any) => match[1]);
  return [...inline, ...references];
}

function headingText(line: string): string | undefined {
  const match = /^#{1,6}\s+(.+?)\s*#*\s*$/.exec(line);
  if (!match) return undefined;
  return match[1]
    .replace(/!\[([^\]]*)\]\([^)]+\)/g, '$1')
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
    .replace(/<[^>]+>/g, '')
    .replace(/[`*_~]/g, '');
}

async function markdownAnchors(
  file: string,
  GithubSlugger: any,
  cache: Map<string, Set<string>>,
): Promise<Set<string>> {
  const cached = cache.get(file);
  if (cached) return cached;
  const slugger = new GithubSlugger();
  const anchors = new Set<string>();
  let fenced = false;
  for (const line of (await readFile(file, 'utf8')).split('\n')) {
    if (/^\s*```/.test(line)) {
      fenced = !fenced;
      continue;
    }
    if (fenced) continue;
    const heading = headingText(line);
    if (heading !== undefined) anchors.add(slugger.slug(heading));
  }
  cache.set(file, anchors);
  return anchors;
}

async function checkLocalLinks(files: string[]): Promise<void> {
  const { default: GithubSlugger }: any = await import(githubSluggerModule);
  const anchorCache = new Map<string, Set<string>>();
  const missing: string[] = [];
  for (const file of files) {
    const markdown = await readFile(file, 'utf8');
    for (const target of markdownTargets(markdown)) {
      if (/^[a-z]+:/i.test(target)) continue;
      const [targetPath, fragment] = target.split('#');
      const local = decodeURIComponent(targetPath);
      const resolved = local.length === 0 ? file : path.resolve(path.dirname(file), local);
      try {
        const targetStat = await stat(resolved);
        if (fragment !== undefined && targetStat.isFile() && resolved.endsWith('.md')) {
          const anchors = await markdownAnchors(resolved, GithubSlugger, anchorCache);
          const anchor = decodeURIComponent(fragment);
          if (!anchors.has(anchor)) missing.push(`${path.relative(root, file)} -> ${target}`);
        }
      } catch (error: any) {
        if (error.code !== 'ENOENT') throw error;
        missing.push(`${path.relative(root, file)} -> ${target}`);
      }
    }
  }
  if (missing.length === 0) return;
  console.error(`Broken documentation links or anchors:\n${missing.join('\n')}`);
  process.exitCode = 1;
}

function normalizeContract(value: string): string {
  return value.replace(/\s+/g, ' ').trim();
}

async function checkAdrContracts(): Promise<void> {
  const interfaceNames = [
    'application.md',
    'http.md',
    'websocket.md',
    'application-events.md',
    'jobs.md',
    'middleware.md',
  ];
  const adrFiles = (await readdir(path.join(root, 'docs', 'adr')))
    .filter((file: string) => file.endsWith('.md'))
    .map((file: string) => path.join(root, 'docs', 'adr', file));
  const interfaceFiles = interfaceNames.map((file: string) =>
    path.join(root, 'docs', 'interface', file),
  );
  const occurrences = new Map<string, Array<{ file: string; text: string }>>();
  const markerPattern =
    /<!-- adr-contract:([a-z0-9.-]+) -->[ \t]*\r?\n(?:[ \t]*\r?\n)*([\s\S]*?)(?=\r?\n[ \t]*\r?\n|$)/g;

  for (const file of [...adrFiles, ...interfaceFiles]) {
    const markdown = await readFile(file, 'utf8');
    for (const match of markdown.matchAll(markerPattern)) {
      const entries = occurrences.get(match[1]) ?? [];
      entries.push({ file, text: normalizeContract(match[2]) });
      occurrences.set(match[1], entries);
    }
  }

  const errors: string[] = [];
  for (const file of interfaceFiles) {
    if (
      ![...occurrences.values()].some((entries) => entries.some((entry) => entry.file === file))
    ) {
      errors.push(`${path.relative(root, file)} has no ADR contract`);
    }
  }
  for (const [id, entries] of occurrences) {
    const adr = entries.filter((entry) =>
      entry.file.includes(`${path.sep}docs${path.sep}adr${path.sep}`),
    );
    const summary = entries.filter((entry) =>
      entry.file.includes(`${path.sep}docs${path.sep}interface${path.sep}`),
    );
    if (adr.length !== 1 || summary.length !== 1) {
      errors.push(`${id} must occur once in ADR and once in capability summary`);
      continue;
    }
    if (adr[0].text !== summary[0].text) {
      errors.push(
        `${id} differs between ${path.relative(root, adr[0].file)} and ${path.relative(root, summary[0].file)}`,
      );
    }
  }
  if (errors.length === 0) return;
  throw new Error(`ADR capability contracts are inconsistent:\n${errors.join('\n')}`);
}

async function documentationFiles(): Promise<string[]> {
  const docs = (await listFiles(path.join(root, 'docs')))
    .filter((file: string) => file.endsWith('.md'))
    .map((file: string) => path.join(root, 'docs', file));
  return [path.join(root, 'AGENTS.md'), path.join(root, 'README.md'), ...docs];
}

async function checkGenerated(expectedRoot: any, actualRoot: any) {
  const expectedFiles = await generatedFiles(expectedRoot);
  const actualFiles = await generatedFiles(actualRoot);
  const expectedSet = new Set(expectedFiles);
  const actualSet = new Set(actualFiles);
  const missing = actualFiles.filter((file: any) => !expectedSet.has(file));
  const extra = expectedFiles.filter((file: any) => !actualSet.has(file));
  const changed: any[] = [];

  for (const file of actualFiles.filter((candidate: any) => expectedSet.has(candidate))) {
    const [expected, actual] = await Promise.all([
      readFile(path.join(expectedRoot, file)),
      readFile(path.join(actualRoot, file)),
    ]);
    if (!expected.equals(actual)) changed.push(file);
  }

  if (missing.length === 0 && extra.length === 0 && changed.length === 0) return;
  if (missing.length > 0) console.error(`Missing generated files: ${missing.join(', ')}`);
  if (extra.length > 0) console.error(`Extra generated files: ${extra.join(', ')}`);
  if (changed.length > 0) console.error(`Outdated generated files: ${changed.join(', ')}`);
  console.error('Run npm run docs:build and commit the generated documentation.');
  process.exitCode = 1;
}

const command = process.argv[2];
const docsRoot = path.join(root, 'docs');

if (command === 'build') {
  await rm(path.join(docsRoot, 'API.md'), { force: true });
  await rm(path.join(docsRoot, 'api'), { force: true, recursive: true });
  await generate(docsRoot);
  await checkAdrContracts();
  await checkLocalLinks(await documentationFiles());
} else if (command === 'check') {
  const temporaryRoot = await mkdtemp(path.join(tmpdir(), 'daevox-docs-'));
  try {
    await generate(temporaryRoot);
    await checkGenerated(docsRoot, temporaryRoot);
    await checkAdrContracts();
    await checkLocalLinks(await documentationFiles());
  } finally {
    await rm(temporaryRoot, { force: true, recursive: true });
  }
} else {
  console.error('Usage: node scripts/docs.ts <build|check>');
  process.exitCode = 2;
}
